### ISSUE TITLE
Error when running on device

### ISSUE THREAD

**Issue by xpdavidx** [rolandleth/LTHPasscodeViewController#153]
Running on simulator it work perfectly with Xcode 7.3.1.
But running on device I'm getting this error:

`Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_LAContext", referenced from:
      objc-class-ref in LTHPasscodeViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by rolandleth** [comment]
Have you tried linking the `LocalAuthentication` framework?

**Comment by xpdavidx** [comment]
Perfect, worked. Thanks a lot. I spend already more than an hour. :)
